// Code generated by cmd/cgo; DO NOT EDIT.

//line C:\Users\leeki\go\src\ch14\cgo\example2\main.go:1:1
package main

import "fmt"

/*
extern int add(int a, int b);
*/
import _ "unsafe"

//export doubler
func doubler(i int) int {
	return i * 2
} // export 주석으로 c코드로 go함수 노출

func main() {
	sum := ( /*line :16:9*/_Cfunc_add /*line :16:13*/)(3, 2)
	fmt.Println(sum)
}
